version: '3'
services:
    master:
        image: eeacms/jenkins-master
        ports:
            - "8081:8080"
        environment:
            - JAVA_OPTS=-Xmx2048m
        volumes:
            - jenkins-master:/var/jenkins_home

    worker:
        image: eeacms/jenkins-slave
        environment:
            JAVA_OPTS: Djenkins.install.runSetupWizard=false
            JENKINS_MASTER: "http://master:8080"
            JENKINS_NAME: "worker"
            JENKINS_USER: "admin"
            JENKINS_PASS: "admin"
            JENKINS_RETRY: "10"
        volumes:
            - jenkins-worker:/var/jenkins_home/worker

volumes:
    jenkins-master:
    jenkins-worker: