version: '3.1'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8081:8080'
            - '50000:50000'
        build: ./jenkins-docker/master
        restart: always
        volumes:
          - jenkins_data:/var/jenkins_home
        networks:
          - ci_net
    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        build: ./jenkins-docker/slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins
        networks:
            - ci_net
    registry:
        environment:
            - REGISTRY_STORAGE_DELETE_ENABLED=true
        ports:
            - '5000:5000'
        restart: always
        container_name: registry
        image: 'registry:2'
        depends_on:
            - jenkins
        networks:
            - ci_net
networks:
  ci_net:
volumes:
  jenkins_data:
