version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_znieczu:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: znieczu
    networks:
      - postgres

  znieczu-back:
    container_name: znieczu-back
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/znieczu-back
    command: bash start.sh
    depends_on:
      - db
      - znieczu-front
    networks:
      - nginx_network

  znieczu-front:
    image: localhost:5000/znieczu-front
    volumes:
      - .:/znieczu-front
    networks:
      - frontend

  nginx:
    image: nginx:1.13
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - znieczu-front
      - znieczu-back
      - db
    networks:
      - nginx_network

#  celery:
#    build:
#      context: .
#      dockerfile: backend/Dockerfile
#    command: celery -A backend.znieczu worker -l info
#    volumes:
#      - .:/backend
#    depends_on:
#      - db
#    networks:
#      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  postgres:
    driver: bridge
  frontend:


volumes:
  db_znieczu: