version: '3'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8081:8080'
        image: localhost:5000/jenkins-master
        volumes:
          - jenkins_home:/var/jenkins_home
    jenkins-slave:
        container_name: jenkins-slave
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        image: localhost:5000/jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins
volumes:
  jenkins_home: