# Generated by Django 2.1 on 2019-05-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_walfare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name', 'address'), 'verbose_name_plural': 'Companies'},
        ),
    ]
